### ISSUE TITLE
lua global and local scope: a REPL session should have its "own" context

### ISSUE THREAD

**Issue by wookayin** [ii14/neorepl.nvim#18]
Case 1: local variables are not recognized

```
> local foo = 1
> foo
< nil                   -- should be 1 (foo)
```

(Note) It seems what REPL does is same as `:lua local foo = 1` then `:lua print(foo)`, which also prints nil because the `local` scope is bind to one `:lua` eval command.

Case 2:

```
> bar = 3 
> bar
< 3                     -- OK
  _G.bar
< nil                   -- should be 3 (_G.bar should be same as bar)
```

(Note) When executing these lines in a vim cmdline, e.g. `:lua bar = 3` then `lua print(_G.bar)` works as expected.

Case 3:
```
> _G.baz = 10
> baz
10                      -- works OK, a symbol is looked up on the global `_G` table
```

**Comment by ii14** [comment]
All of this works as intended.

1. Local variables cannot be recognized between prompts, this is an inherent limitation of Lua REPLs. Local variables are local to a "chunk", and chunks are immutable. Once you parse Lua code into a chunk/function you cannot append to it any more code. From that point ~~names of the variables are gone~~, and the compiled bytecode internally assigns them indices and refers to them only in that way. (You can still kinda access local variables through the `debug` module, but it's only possible when you're in the middle of execution, in the debug hook.)
2. Because it's impossible to have real local variables, code runs with its own environment. If you want to create "local" variables, simply create a global one like this, and it will not leak to the actual global environment or to other REPL buffers/instances. If a variable does not exist in REPL's environment, it falls back to neovim's global variables. (See http://www.lua.org/manual/5.1/manual.html#2.3 and http://www.lua.org/manual/5.1/manual.html#pdf-setfenv)
3. To still allow modifying neovim's environment, you can access it through `_G`.

This is shortly mentioned in the README, but maybe the explanation is not clear enough. And it probably should be included in vimdoc as well.
